/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

#include <lib/core/DataModelTypes.h>

namespace chip {
namespace app {
namespace Clusters {
namespace ContentControl {
namespace Commands {
namespace UpdatePIN {
inline constexpr CommandId Id = 0x00000000;
} // namespace UpdatePIN

namespace ResetPIN {
inline constexpr CommandId Id = 0x00000001;
} // namespace ResetPIN

namespace ResetPINResponse {
inline constexpr CommandId Id = 0x00000002;
} // namespace ResetPINResponse

namespace Enable {
inline constexpr CommandId Id = 0x00000003;
} // namespace Enable

namespace Disable {
inline constexpr CommandId Id = 0x00000004;
} // namespace Disable

namespace AddBonusTime {
inline constexpr CommandId Id = 0x00000005;
} // namespace AddBonusTime

namespace SetScreenDailyTime {
inline constexpr CommandId Id = 0x00000006;
} // namespace SetScreenDailyTime

namespace BlockUnratedContent {
inline constexpr CommandId Id = 0x00000007;
} // namespace BlockUnratedContent

namespace UnblockUnratedContent {
inline constexpr CommandId Id = 0x00000008;
} // namespace UnblockUnratedContent

namespace SetOnDemandRatingThreshold {
inline constexpr CommandId Id = 0x00000009;
} // namespace SetOnDemandRatingThreshold

namespace SetScheduledContentRatingThreshold {
inline constexpr CommandId Id = 0x0000000A;
} // namespace SetScheduledContentRatingThreshold

} // Commands
} // ContentControl
} // Clusters
} // app
} // chip
